#!/bin/bash

datamodel-codegen \
    --url https://github.com/tapis-project/tapipy/raw/563ed2fa7e2b2aa1bb8bb1c0738409be10604210/tapipy/resources/openapi_v3-jobs.yml \
    --output src/mri_actor_utils/jobs.py \
    --enum-field-as-literal all \
    --use-standard-collections \
    --use-union-operator \
    --target-python-version 3.12 \
    --use-schema-description \
    --output-model-type pydantic_v2.BaseModel \
    --input-file-type openapi 


# # for this one, need to adjust a few min_item -> min_length
# # also need to delete ListTypeEnum
# datamodel-codegen \
#     --url https://github.com/tapis-project/tapipy/raw/main/tapipy/resources/openapi_v3-apps.yml \
#     --output src/mri_actor_utils/apps.py \
#     --enum-field-as-literal all \
#     --use-standard-collections \
#     --use-union-operator \
#     --target-python-version 3.12 \
#     --use-schema-description \
#     --field-constraints \
#     --collapse-root-models

